import { DiffEditor } from "@monaco-editor/react";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data } = api.source.file.useQuery({ file: "_app.tsx" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Mod <span className="text-purple-400">T3</span> App
          </h1>

          {data ? (
            <DiffEditor
              loading={null}
              className="h-[50vh] w-full"
              original={data?.original}
              modified={data?.modified}
              language={data?.language}
            />
          ) : (
            <div className="text-lg text-white">Applying codemod...</div>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
